### ISSUE TITLE
Depending on @angular/cdk causes issues

### ISSUE THREAD

**Issue by Splaktar** [nitayneeman/schematics-utilities#17]
I just wanted to give you a heads up that depending upon the Angular CDK
https://github.com/nitayneeman/schematics-utilities/blob/96bf7f4f273d3fa3eaccdd9320fdca9034aa1248/package.json#L40
in order to pull in the schematics, is not ideal and causes problems like https://github.com/angular/components/issues/18020.

I think that it would be safer to copy the schematic code from the CDK over into this repo just like you do with Angular Material.

We're going to try to put some checks in place in Angular Material's schematics, so that this conflict doesn't break someone's project. But the reality is that projects shouldn't be pulling in `@angular/cdk` in order to use the private schematic helpers. They need to copy them into their own project (and take over maintenance of them in their project) instead.

**Comment by nitayneeman** [comment]
Hey,

Assuming `@angular/cdk`'s schematic code is intended only for private usages, I don't see any other option besides copy the files (as already done within the project). 
I'll try to handle that shortly.

Thanks for notifying me!
