### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by thigrand** [nitayneeman/schematics-utilities#25]
Hi dude, 
Can you update @angular/cdk (@angular/components) package and release new version?
There are some nice changes there

**Comment by nitayneeman** [comment]
Hey,

Since v2.0.0 `@angular/cdk` isn't a dependency - you can upgrade your `@angular/cdk` and `schematics-utilities` to achieve the latest features.

Check out this reference for more information: https://github.com/nitayneeman/schematics-utilities/issues/17

**Comment by thigrand** [comment]
Actually i find a way to get access directly to the methods. So i'm able to delete schematics-utilities package. 
Thanks for you answer, and your work. 
Best regards
